### ISSUE TITLE
Latin9 encoding support?

### ISSUE THREAD

**Issue by glodov** [nodejs/string_decoder#20]
Is this possible to extend the list of supported encodings with latin9?

I have an error when trying to use it:
As ISO-8859-15
```
TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: ISO-8859-15
    at normalizeEncoding (string_decoder.js:57:13)
    at new StringDecoder (string_decoder.js:71:19)
```
As latin9
```
TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: latin9
    at normalizeEncoding (string_decoder.js:57:13)
    at new StringDecoder (string_decoder.js:71:19)
```

**Comment by mcollina** [comment]
You are likely reporting this to the wrong project, please report it to node.js itself (this module is just an extraction to be used in the browser).
